application: enen-pazzle
version: 1
runtime: python
api_version: 1

handlers:
- url: /Main.swf.*
  static_files: Main.swf
  upload: Main.swf

- url: /style.css
  static_files: style.css
  upload: style.css

- url: /api.*
  script: api.py

- url: /.*
  script: main_page.py
